//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int IDChiTietHD { get; set; }
        public Nullable<int> IDHD { get; set; }
        public Nullable<int> IDMH { get; set; }
        public Nullable<int> SoluongMH { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
